apiVersion : apps/v1
kind : Deployment
metadata :
  name : exipration-depl
spec :
  replicas : 1
  selector :
    matchLabels : 
      app : exipration
  template :
    metadata :
     labels :
      app : exipration
    spec :
      containers :
        - name  : exipration
          image : muhammedmustafa/exipration
          env :
            - name : NATS_CLIENT_ID
              valueFrom :
                fieldRef :
                  fieldPath : metadata.name
            - name  : NATS_URL
              value : 'http://nats-srv:4222'
            - name  : NATS_CLUSTER_ID
              value : ticketing
            - name  : REDIS_HOST
              value : exipration-redis-srv
